"""add timestamps to food items

Revision ID: 81602e0da546
Revises: ba9e0a0b7f98
Create Date: 2026-07-14 05:04:26.477140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81602e0da546'
down_revision: Union[str, Sequence[str], None] = 'ba9e0a0b7f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'food_items',
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=True
        )
    )

    op.add_column(
        'food_items',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            nullable=True
        )
    )

    op.execute(
        """
        UPDATE food_items
        SET created_at = NOW(),
            updated_at = NOW()
        """
    )

    op.alter_column(
        'food_items',
        'created_at',
        nullable=False
    )

    op.alter_column(
        'food_items',
        'updated_at',
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_items', 'updated_at')
    op.drop_column('food_items', 'created_at')
    # ### end Alembic commands ###
