"""add food brand

Revision ID: ba9e0a0b7f98
Revises: 65aa068bdd10
Create Date: 2026-07-14 04:55:05.583526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba9e0a0b7f98'
down_revision: Union[str, Sequence[str], None] = '65aa068bdd10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_items', sa.Column('brand', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_items', 'brand')
    # ### end Alembic commands ###
